version: '3'

services:

  react_app:
    build:
      context: ./
      dockerfile: ./docker/build_files/Dockerfile
    container_name: jspf-web
    restart: always
    volumes:
      - ./docker/storage:/usr/src/app/storage
      - ./docker/public/uploads:/usr/src/app/public/uploads
    env_file:
    - .env
    ports:
    - '3000:3000'